<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>eu.ralph-schuster</groupId>
		<artifactId>libs</artifactId>
		<version>6.0.0-SNAPSHOT</version>
	</parent>
  	
	<properties>
		<project.home>https://github.com/technicalguru/rslibs</project.home>
		<jersey.version>3.1.12</jersey.version>
	</properties>

	<artifactId>jersey-client</artifactId>
 	<packaging>jar</packaging>
	<name>${project.groupId}.${project.artifactId}</name>
  	<description>Basic implementation to create RS WS clients with Jersey</description>
	<url>https://github.com/technicalguru/rslibs</url>
	
	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>baselib</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
		    <groupId>org.glassfish.jersey.core</groupId>
		    <artifactId>jersey-client</artifactId>
		    <version>${jersey.version}</version>
		</dependency>
		<dependency>
		    <groupId>org.glassfish.jersey.inject</groupId>
		    <artifactId>jersey-hk2</artifactId>
		    <version>${jersey.version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.glassfish.jersey.connectors/jersey-apache-connector -->
		<dependency>
		    <groupId>org.glassfish.jersey.connectors</groupId>
		    <artifactId>jersey-apache-connector</artifactId>
		    <version>${jersey.version}</version>
		</dependency>
		<dependency>
		    <groupId>org.glassfish.jersey.media</groupId>
		    <artifactId>jersey-media-json-jackson</artifactId>
		    <version>${jersey.version}</version>
		</dependency>
		
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<configuration>
					<header><![CDATA[<a href="${project.home}" target="_new">Visit the ${project.name} Homepage</a>]]></header>
					<detectJavaApiLink>false</detectJavaApiLink>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>